# Generated by Django 3.2 on 2022-03-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
